set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64_be)

set(TOOLCHAIN_ROOT_DEFAULT "$ENV{AARCH64_BE_TOOLCHAIN_ROOT}")
if(NOT TOOLCHAIN_ROOT_DEFAULT)
    set(TOOLCHAIN_ROOT_DEFAULT "$ENV{ARM_GNU_AARCH64_BE_HOME}")
endif()

set(TOOLCHAIN_ROOT "${TOOLCHAIN_ROOT_DEFAULT}"
    CACHE PATH "Arm GNU Toolchain root for aarch64_be-none-linux-gnu")
set(TOOLCHAIN_PREFIX aarch64_be-none-linux-gnu)

if(TOOLCHAIN_ROOT)
    set(TOOLCHAIN_BIN_PATH "${TOOLCHAIN_ROOT}/bin")
endif()

find_program(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++ HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-gcc HINTS ${TOOLCHAIN_BIN_PATH})

find_program(CMAKE_AR ${TOOLCHAIN_PREFIX}-ar HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}-ranlib HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_STRIP ${TOOLCHAIN_PREFIX}-strip HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}-objdump HINTS ${TOOLCHAIN_BIN_PATH})

set(TOOLCHAIN_SYSROOT_DEFAULT "$ENV{AARCH64_BE_SYSROOT}")
if(TOOLCHAIN_SYSROOT_DEFAULT)
    set(TOOLCHAIN_SYSROOT "${TOOLCHAIN_SYSROOT_DEFAULT}"
        CACHE PATH "Sysroot for aarch64_be-none-linux-gnu")
endif()

if(NOT TOOLCHAIN_SYSROOT AND CMAKE_C_COMPILER)
    execute_process(
        COMMAND ${CMAKE_C_COMPILER} --print-sysroot
        OUTPUT_VARIABLE TOOLCHAIN_DETECTED_SYSROOT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    if(TOOLCHAIN_DETECTED_SYSROOT)
        set(TOOLCHAIN_SYSROOT "${TOOLCHAIN_DETECTED_SYSROOT}"
            CACHE PATH "Sysroot for aarch64_be-none-linux-gnu")
    endif()
endif()

if(TOOLCHAIN_SYSROOT)
    set(CMAKE_SYSROOT "${TOOLCHAIN_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH)
if(TOOLCHAIN_SYSROOT)
    list(APPEND CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_SYSROOT}")
endif()
if(TOOLCHAIN_ROOT)
    list(APPEND CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_ROOT}/${TOOLCHAIN_PREFIX}")
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TOOLCHAIN_DETECTED_COMPILER "gcc")
set(TOOLCHAIN_DETECTED_LINKER "gnu-ld")
set(TOOLCHAIN_DETECTED_PLATFORM "linux")
